name: Generate index

# Trigger this workflow on any push to main branch
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate index
      - name: Generate index
        run: |
          OUTPUT="index"
          > "$OUTPUT"  # clear previous index
          for file in *; do
            [[ "$file" == "$OUTPUT" ]] && continue   # skip index itself
            [[ -f "$file" ]] || continue            # skip folders
            printf "\n===== %s =====\n\n" "$file" >> "$OUTPUT"
            cat "$file" >> "$OUTPUT"
            printf "\n" >> "$OUTPUT"
          done

      # Step 3: Commit and push index
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/kuryletso/my-cheats.git
          git add index
          git commit -m "Auto-generate index" || exit 0
          git push origin main
